name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Astro globally
        run: bun add -g astro@latest

      - name: Install Frontend dependencies
        working-directory: frontend
        run: |
          bun install

      - name: Build Backend
        working-directory: backend
        run: |
          bun install
          bun run build:ui

      - name: Run Tests
        run: bun run test --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
